import warnings
from collections import defaultdict

import numpy as np
import pandas as pd
import statsmodels.api as sm
from scipy.stats import chi2
from statsmodels.discrete.discrete_model import NegativeBinomial
from statsmodels.stats.multitest import multipletests
from statsmodels.tools.sm_exceptions import (
    ConvergenceWarning,
    HessianInversionWarning,
)
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
from matplotlib.patches import Rectangle
from matplotlib.patches import Rectangle, Patch


def compute_nb_matrix_analysis(
    df_defects,
    df_cctv_filtered,
    selected_materials,
    factors_cat,
    get_categories_order,
    pipe_id="Pipe_ID",
    defect_col="Defect_code_full",
    min_pipes=1,
    min_positive_pipes=0,
    min_positive_pipes_per_group=1,
    alpha=0.05,
    selected_defects=None,
    cov_type="HC0",
    maxiter=1000,
    max_clr=20,
    reject_runtime_warnings=True,
    print_model_warnings=True,
):
    """
    Run pipe-level Negative Binomial analyses.

    For every Material x Factor combination:

    1. Test the factor as a whole with a likelihood-ratio test.
    2. Compare each category against all remaining valid categories.
    3. Calculate the Incidence Rate Ratio (IRR).
    4. Apply Benjamini-Hochberg FDR correction.
    5. Retain only IRRs that satisfy the stability criteria.

    Stability criteria
    ------------------
    A category-vs-rest IRR is retained only when:

    - The category contains at least ``min_pipes`` pipes.
    - The defect occurs in at least ``min_positive_pipes_per_group``
      pipes in both the category and the rest of the categories combined.
    - The Negative Binomial model converges.
    - No ConvergenceWarning occurs.
    - No HessianInversionWarning occurs.
    - If ``reject_runtime_warnings=True``, no RuntimeWarning occurs.
    - Coefficients, SEs, p-values, alpha and likelihood are finite.
    - IRR and confidence limits are finite and positive.
    - CLR = CI_high / CI_low <= ``max_clr`` when max_clr is not None.

    Warning behaviour
    -----------------
    All warnings are captured silently.

    Warnings from models that are later discarded are NOT printed.

    Warnings are printed only when the corresponding model passes all
    filters and its IRR is retained.

    All captured warnings are nevertheless stored in ``warning_log`` for
    traceability.

    Notes
    -----
    ``irr`` and ``log2_irr`` contain only stable IRRs.

    p-values from numerically valid cell models are retained for FDR
    correction even if their IRR is subsequently excluded because its
    confidence interval is too wide.

    Returns
    -------
    results : dict
        Nested dictionary containing the results.

    relevant_defects : dict
        Defects with at least one significant, stable final result.

    defect_order : list
        Order of defects used in the result matrices.
    """

    # =========================================================
    # VALIDATE PARAMETERS
    # =========================================================

    if min_pipes < 1:
        raise ValueError(
            "min_pipes must be at least 1."
        )

    if min_positive_pipes < 0:
        raise ValueError(
            "min_positive_pipes must be zero or greater."
        )

    if min_positive_pipes_per_group < 0:
        raise ValueError(
            "min_positive_pipes_per_group must be zero or greater."
        )

    if max_clr is not None and max_clr < 1:
        raise ValueError(
            "max_clr must be at least 1, "
            "or None to disable the CLR filter."
        )

    # =========================================================
    # HELPER FUNCTIONS
    # =========================================================

    def _warning_flags(caught_warnings):
        """
        Identify important warning types generated by one model fit.
        """

        return {
            "convergence": any(
                issubclass(w.category, ConvergenceWarning)
                for w in caught_warnings
            ),
            "hessian": any(
                issubclass(w.category, HessianInversionWarning)
                for w in caught_warnings
            ),
            "runtime": any(
                issubclass(w.category, RuntimeWarning)
                for w in caught_warnings
            ),
        }

    def _record_warnings(
        caught_warnings,
        warning_store,
        *,
        material,
        factor,
        defect,
        model_type,
        category=None,
    ):
        """
        Store unique warnings generated by a model.

        IMPORTANT:
        This function does NOT print warnings.

        It returns the warning records corresponding to the current model
        so they can be printed later only if the model is retained.
        """

        records = []
        seen = set()

        for warning_item in caught_warnings:

            warning_name = warning_item.category.__name__
            warning_message = str(warning_item.message)

            key = (
                warning_name,
                warning_message,
            )

            if key in seen:
                continue

            seen.add(key)

            record = {
                "material": material,
                "factor": factor,
                "defect": defect,
                "category": category,
                "model_type": model_type,
                "warning_type": warning_name,
                "message": warning_message,
                "retained": False,
            }

            # Same dictionary object is stored in both lists.
            # If retained is changed later, warning_store is updated too.
            warning_store.append(record)
            records.append(record)

        return records

    def _mark_warnings_retained(warning_records):
        """
        Mark warnings as belonging to a retained model.
        """

        for record in warning_records:
            record["retained"] = True

    def _print_retained_warnings(warning_records):
        """
        Print warnings ONLY for a model that survived every filter.
        """

        if not print_model_warnings:
            return

        for record in warning_records:

            message = (
                "WARNING IN RETAINED MODEL | "
                f"Material={record['material']} | "
                f"Factor={record['factor']} | "
                f"Defect={record['defect']} | "
            )

            if record["category"] is not None:
                message += (
                    f"Category={record['category']} | "
                )

            message += (
                f"Model={record['model_type']} | "
                f"{record['warning_type']}: "
                f"{record['message']}"
            )

            print(message)

    def _get_alpha(result):
        """
        Safely extract the Negative Binomial dispersion parameter.
        """

        try:

            if hasattr(result.params, "get"):
                return result.params.get(
                    "alpha",
                    np.nan,
                )

            return result.params[-1]

        except Exception:
            return np.nan

    def _fit_problems(
        result,
        caught_warnings,
        *,
        require_bse=False,
        require_pvalues=False,
    ):
        """
        Check whether a fitted Negative Binomial model is numerically valid.

        Returns
        -------
        list
            Empty list if valid, otherwise descriptions of the problems.
        """

        problems = []

        flags = _warning_flags(
            caught_warnings
        )

        # -----------------------------------------------------
        # Convergence
        # -----------------------------------------------------

        converged = bool(
            result.mle_retvals.get(
                "converged",
                False,
            )
        )

        if not converged:
            problems.append(
                "did not converge"
            )

        if flags["convergence"]:
            problems.append(
                "ConvergenceWarning"
            )

        if flags["hessian"]:
            problems.append(
                "Hessian inversion warning"
            )

        # -----------------------------------------------------
        # Runtime warnings
        # -----------------------------------------------------

        if (
            reject_runtime_warnings
            and flags["runtime"]
        ):
            problems.append(
                "RuntimeWarning"
            )

        # -----------------------------------------------------
        # Log-likelihood
        # -----------------------------------------------------

        try:

            if not np.isfinite(
                result.llf
            ):
                problems.append(
                    "non-finite log-likelihood"
                )

        except Exception:

            problems.append(
                "log-likelihood unavailable"
            )

        # -----------------------------------------------------
        # Parameters
        # -----------------------------------------------------

        try:

            params_array = np.asarray(
                result.params,
                dtype=float,
            )

            if not np.all(
                np.isfinite(params_array)
            ):
                problems.append(
                    "non-finite parameters"
                )

        except Exception:

            problems.append(
                "parameters unavailable"
            )

        # -----------------------------------------------------
        # Dispersion parameter alpha
        # -----------------------------------------------------

        model_alpha = _get_alpha(
            result
        )

        if not np.isfinite(
            model_alpha
        ):
            problems.append(
                "non-finite alpha"
            )

        elif model_alpha <= 0:
            problems.append(
                "non-positive alpha"
            )

        # -----------------------------------------------------
        # Standard errors
        # -----------------------------------------------------

        if require_bse:

            try:

                bse_array = np.asarray(
                    result.bse,
                    dtype=float,
                )

                if not np.all(
                    np.isfinite(bse_array)
                ):
                    problems.append(
                        "non-finite standard errors"
                    )

            except Exception:

                problems.append(
                    "standard errors unavailable"
                )

        # -----------------------------------------------------
        # p-values
        # -----------------------------------------------------

        if require_pvalues:

            try:

                pvalues_array = np.asarray(
                    result.pvalues,
                    dtype=float,
                )

                if not np.all(
                    np.isfinite(pvalues_array)
                ):
                    problems.append(
                        "non-finite p-values"
                    )

            except Exception:

                problems.append(
                    "p-values unavailable"
                )

        return problems

    # =========================================================
    # SETUP
    # =========================================================

    results = defaultdict(dict)

    if selected_defects is None:

        defect_order = (
            df_defects[defect_col]
            .value_counts()
            .index
            .tolist()
        )

    else:

        defect_order = list(
            selected_defects
        )

    category_order = (
        get_categories_order()
    )

    # =========================================================
    # MATERIAL LOOP
    # =========================================================

    for material in selected_materials:

        print(
            f"\n{'=' * 70}"
        )
        print(
            f"Material: {material}"
        )
        print(
            "=" * 70
        )

        material_pipes = (
            df_cctv_filtered.loc[
                df_cctv_filtered["Material"]
                == material
            ]
            .copy()
        )

        material_defects = (
            df_defects.loc[
                df_defects["Material"]
                == material
            ]
            .copy()
        )

        # =====================================================
        # FACTOR LOOP
        # =====================================================

        for factor_name in factors_cat:

            print(
                f"\nFactor: {factor_name}"
            )

            # Stores ALL warnings generated for this
            # Material x Factor analysis.
            factor_warning_log = []

            all_cats = (
                category_order[
                    factor_name
                ]
            )

            # =================================================
            # PIPE CATEGORIES
            # =================================================

            pipe_categories = (
                material_pipes[
                    [
                        pipe_id,
                        factor_name,
                    ]
                ]
                .dropna(
                    subset=[
                        pipe_id,
                        factor_name,
                    ]
                )
                .drop_duplicates()
            )

            categories_per_pipe = (
                pipe_categories
                .groupby(
                    pipe_id
                )[factor_name]
                .nunique()
            )

            conflicting_pipes = (
                categories_per_pipe[
                    categories_per_pipe > 1
                ]
            )

            if not conflicting_pipes.empty:

                raise ValueError(
                    f"{len(conflicting_pipes)} pipes "
                    f"have more than one value of "
                    f"'{factor_name}' for material "
                    f"'{material}'. Resolve these "
                    "conflicts before running the analysis."
                )

            pipes = (
                pipe_categories
                .drop_duplicates(
                    subset=pipe_id
                )
                .copy()
            )

            pipe_counts = (
                pipes
                .groupby(
                    factor_name
                )[pipe_id]
                .nunique()
            )

            # =================================================
            # VALID CATEGORIES
            # =================================================

            valid_cats = [
                category
                for category in all_cats
                if pipe_counts.get(
                    category,
                    0,
                ) >= min_pipes
            ]

            print(
                "Valid categories:"
            )

            for category in valid_cats:

                print(
                    f"  {category}: "
                    f"{pipe_counts.get(category, 0)} pipes"
                )

            # =================================================
            # NOT ENOUGH CATEGORIES
            # =================================================

            if len(valid_cats) < 2:

                results[
                    material
                ][factor_name] = {

                    "irr": None,
                    "log2_irr": None,
                    "ci_low": None,
                    "ci_high": None,
                    "clr": None,

                    "stable_irr": None,
                    "valid_cell_model": None,
                    "cell_status": None,

                    "pval_raw": None,
                    "pval_fdr": None,
                    "significant_cell": None,

                    "positive_pipes_category": None,
                    "positive_pipes_rest": None,

                    "pval_omnibus": None,
                    "qval_omnibus": None,
                    "significant_omnibus": None,

                    "significant_final": None,

                    "diagnostics": None,

                    "warning_log": (
                        pd.DataFrame()
                    ),

                    "valid_categories": (
                        valid_cats
                    ),

                    "all_categories": (
                        all_cats
                    ),

                    "max_clr": max_clr,

                    "excluded": True,
                }

                continue

            # =================================================
            # KEEP ONLY VALID CATEGORIES
            # =================================================

            pipes = (
                pipes.loc[
                    pipes[factor_name]
                    .isin(valid_cats)
                ]
                .copy()
            )

            # Preserve desired order explicitly.
            pipes[factor_name] = (
                pd.Categorical(
                    pipes[factor_name],
                    categories=valid_cats,
                    ordered=True,
                )
            )

            defects_in_valid_pipes = (
                material_defects.loc[
                    material_defects[
                        pipe_id
                    ].isin(
                        pipes[pipe_id]
                    )
                ]
            )

            defect_counts = (
                defects_in_valid_pipes
                .groupby(
                    [
                        pipe_id,
                        defect_col,
                    ]
                )
                .size()
                .unstack(
                    fill_value=0
                )
            )

            # =================================================
            # RESULT MATRICES
            # =================================================

            irr_df = pd.DataFrame(
                np.nan,
                index=defect_order,
                columns=valid_cats,
            )

            log2_irr_df = (
                irr_df.copy()
            )

            ci_low_df = (
                irr_df.copy()
            )

            ci_high_df = (
                irr_df.copy()
            )

            clr_df = (
                irr_df.copy()
            )

            stable_irr_df = (
                pd.DataFrame(
                    False,
                    index=defect_order,
                    columns=valid_cats,
                    dtype=bool,
                )
            )

            valid_cell_model_df = (
                pd.DataFrame(
                    False,
                    index=defect_order,
                    columns=valid_cats,
                    dtype=bool,
                )
            )

            cell_status_df = (
                pd.DataFrame(
                    "",
                    index=defect_order,
                    columns=valid_cats,
                    dtype=object,
                )
            )

            pval_df = (
                irr_df.copy()
            )

            positive_category_df = (
                irr_df.copy()
            )

            positive_rest_df = (
                irr_df.copy()
            )

            omnibus_p = pd.Series(
                np.nan,
                index=defect_order,
                dtype=float,
            )

            diagnostics = pd.DataFrame(
                index=defect_order,
                columns=[
                    "n_pipes",
                    "n_positive",
                    "total_defects",
                    "mean_defects_per_pipe",
                    "variance",
                    "pct_zero",
                    "alpha",
                    "converged",
                    "valid_cell_models",
                    "stable_cell_models",
                    "status",
                ],
            )

            # =================================================
            # DEFECT LOOP
            # =================================================

            for defect in defect_order:

                df_model = (
                    pipes[
                        [
                            pipe_id,
                            factor_name,
                        ]
                    ]
                    .copy()
                )

                # =============================================
                # DEFECT COUNTS PER PIPE
                # =============================================

                if (
                    defect
                    in defect_counts.columns
                ):

                    counts = (
                        defect_counts[
                            defect
                        ]
                        .rename(
                            "defect_count"
                        )
                        .reset_index()
                    )

                    df_model = (
                        df_model.merge(
                            counts,
                            on=pipe_id,
                            how="left",
                        )
                    )

                else:

                    df_model[
                        "defect_count"
                    ] = 0

                df_model[
                    "defect_count"
                ] = (
                    df_model[
                        "defect_count"
                    ]
                    .fillna(0)
                    .astype(int)
                )

                # =============================================
                # DESCRIPTIVE DIAGNOSTICS
                # =============================================

                n_pipes = len(
                    df_model
                )

                n_positive = int(
                    (
                        df_model[
                            "defect_count"
                        ] > 0
                    ).sum()
                )

                total_defects = int(
                    df_model[
                        "defect_count"
                    ].sum()
                )

                mean_count = (
                    df_model[
                        "defect_count"
                    ].mean()
                )

                variance_count = (
                    df_model[
                        "defect_count"
                    ].var()
                )

                pct_zero = (
                    100
                    * (
                        df_model[
                            "defect_count"
                        ] == 0
                    ).mean()
                )

                diagnostics.loc[
                    defect,
                    [
                        "n_pipes",
                        "n_positive",
                        "total_defects",
                        "mean_defects_per_pipe",
                        "variance",
                        "pct_zero",
                    ],
                ] = [
                    n_pipes,
                    n_positive,
                    total_defects,
                    mean_count,
                    variance_count,
                    pct_zero,
                ]

                # =============================================
                # NO DEFECTS
                # =============================================

                if total_defects == 0:

                    diagnostics.loc[
                        defect,
                        "status",
                    ] = "no defects"

                    continue

                # =============================================
                # TOO FEW POSITIVE PIPES OVERALL
                # =============================================

                if (
                    n_positive
                    < min_positive_pipes
                ):

                    diagnostics.loc[
                        defect,
                        "status",
                    ] = (
                        "too few positive pipes "
                        f"({n_positive} < "
                        f"{min_positive_pipes})"
                    )

                    continue

                y = (
                    df_model[
                        "defect_count"
                    ]
                    .astype(float)
                )

                # =================================================
                # OMNIBUS MODEL
                # =================================================

                dummies = pd.get_dummies(
                    df_model[
                        factor_name
                    ],
                    drop_first=True,
                    dtype=float,
                )

                X_full = sm.add_constant(
                    dummies,
                    has_constant="add",
                )

                X_null = pd.DataFrame(
                    {
                        "const": 1.0
                    },
                    index=df_model.index,
                )

                try:

                    # -----------------------------------------
                    # FULL MODEL
                    # -----------------------------------------

                    with warnings.catch_warnings(
                        record=True
                    ) as full_warnings:

                        warnings.simplefilter(
                            "always"
                        )

                        full_result = (
                            NegativeBinomial(
                                y,
                                X_full,
                            )
                            .fit(
                                disp=False,
                                cov_type=cov_type,
                                maxiter=maxiter,
                            )
                        )

                    full_warning_records = (
                        _record_warnings(
                            full_warnings,
                            factor_warning_log,
                            material=material,
                            factor=factor_name,
                            defect=defect,
                            model_type=(
                                "omnibus-full"
                            ),
                        )
                    )

                    # -----------------------------------------
                    # NULL MODEL
                    # -----------------------------------------

                    with warnings.catch_warnings(
                        record=True
                    ) as null_warnings:

                        warnings.simplefilter(
                            "always"
                        )

                        null_result = (
                            NegativeBinomial(
                                y,
                                X_null,
                            )
                            .fit(
                                disp=False,
                                cov_type=cov_type,
                                maxiter=maxiter,
                            )
                        )

                    null_warning_records = (
                        _record_warnings(
                            null_warnings,
                            factor_warning_log,
                            material=material,
                            factor=factor_name,
                            defect=defect,
                            model_type=(
                                "omnibus-null"
                            ),
                        )
                    )

                    # -----------------------------------------
                    # CHECK OMNIBUS MODEL
                    # -----------------------------------------

                    full_problems = (
                        _fit_problems(
                            full_result,
                            full_warnings,
                        )
                    )

                    null_problems = (
                        _fit_problems(
                            null_result,
                            null_warnings,
                        )
                    )

                    omnibus_problems = []

                    if full_problems:

                        omnibus_problems.append(
                            "full: "
                            + ", ".join(
                                full_problems
                            )
                        )

                    if null_problems:

                        omnibus_problems.append(
                            "null: "
                            + ", ".join(
                                null_problems
                            )
                        )

                    full_converged = bool(
                        full_result
                        .mle_retvals
                        .get(
                            "converged",
                            False,
                        )
                    )

                    null_converged = bool(
                        null_result
                        .mle_retvals
                        .get(
                            "converged",
                            False,
                        )
                    )

                    diagnostics.loc[
                        defect,
                        "converged",
                    ] = (
                        full_converged
                        and null_converged
                    )

                    # -----------------------------------------
                    # OMNIBUS FAILED
                    # -----------------------------------------

                    if omnibus_problems:

                        message = (
                            "; ".join(
                                omnibus_problems
                            )
                        )

                        diagnostics.loc[
                            defect,
                            "status",
                        ] = (
                            "omnibus invalid: "
                            f"{message}"
                        )

                        # Only the skip reason is printed.
                        # Detailed warnings remain silent.
                        print(
                            "Skipping omnibus model | "
                            f"Material={material} | "
                            f"Factor={factor_name} | "
                            f"Defect={defect} | "
                            f"{message}"
                        )

                        continue

                    # -----------------------------------------
                    # OMNIBUS PASSED
                    # -----------------------------------------

                    model_alpha = (
                        _get_alpha(
                            full_result
                        )
                    )

                    diagnostics.loc[
                        defect,
                        "alpha",
                    ] = model_alpha

                    lr_stat = max(
                        2
                        * (
                            full_result.llf
                            - null_result.llf
                        ),
                        0,
                    )

                    df_diff = (
                        X_full.shape[1]
                        - X_null.shape[1]
                    )

                    omnibus_p.loc[
                        defect
                    ] = chi2.sf(
                        lr_stat,
                        df_diff,
                    )

                    # The omnibus models survived their
                    # numerical filters.
                    _mark_warnings_retained(
                        full_warning_records
                    )

                    _mark_warnings_retained(
                        null_warning_records
                    )

                    # Print warnings ONLY now.
                    _print_retained_warnings(
                        full_warning_records
                    )

                    _print_retained_warnings(
                        null_warning_records
                    )

                except Exception as error:

                    diagnostics.loc[
                        defect,
                        "status",
                    ] = (
                        "omnibus failed: "
                        f"{type(error).__name__}"
                    )

                    print(
                        "Omnibus model failed | "
                        f"Material={material} | "
                        f"Factor={factor_name} | "
                        f"Defect={defect} | "
                        f"{type(error).__name__}: "
                        f"{error}"
                    )

                    continue

                # =================================================
                # CATEGORY VS REST MODELS
                # =================================================

                valid_cell_models = 0
                stable_cell_models = 0

                for category in valid_cats:

                    is_category = (
                        (
                            df_model[
                                factor_name
                            ]
                            == category
                        )
                        .astype(float)
                    )

                    if (
                        is_category.nunique()
                        < 2
                    ):

                        cell_status_df.loc[
                            defect,
                            category,
                        ] = (
                            "only_one_group"
                        )

                        continue

                    # =========================================
                    # POSITIVE PIPES
                    # =========================================

                    positive_pipes_category = int(
                        (
                            (is_category == 1)
                            & (y > 0)
                        ).sum()
                    )

                    positive_pipes_rest = int(
                        (
                            (is_category == 0)
                            & (y > 0)
                        ).sum()
                    )

                    positive_category_df.loc[
                        defect,
                        category,
                    ] = (
                        positive_pipes_category
                    )

                    positive_rest_df.loc[
                        defect,
                        category,
                    ] = (
                        positive_pipes_rest
                    )

                    # =========================================
                    # DATA SUFFICIENCY FILTER
                    # =========================================

                    if (
                        positive_pipes_category
                        < min_positive_pipes_per_group
                        or
                        positive_pipes_rest
                        < min_positive_pipes_per_group
                    ):

                        cell_status_df.loc[
                            defect,
                            category,
                        ] = (
                            "insufficient_positive_pipes"
                        )

                        print(
                            "Skipping cell | "
                            f"Material={material} | "
                            f"Factor={factor_name} | "
                            f"Defect={defect} | "
                            f"Category={category} | "
                            "insufficient positive pipes "
                            f"(category="
                            f"{positive_pipes_category}, "
                            f"rest="
                            f"{positive_pipes_rest}, "
                            "required per group="
                            f"{min_positive_pipes_per_group})"
                        )

                        continue

                    # =========================================
                    # DESIGN MATRIX
                    # =========================================

                    X_cell = pd.DataFrame(
                        {
                            "const": 1.0,
                            "is_category": (
                                is_category
                            ),
                        },
                        index=df_model.index,
                    )

                    try:

                        # =====================================
                        # FIT CELL MODEL
                        # =====================================

                        with warnings.catch_warnings(
                            record=True
                        ) as cell_warnings:

                            warnings.simplefilter(
                                "always"
                            )

                            cell_result = (
                                NegativeBinomial(
                                    y,
                                    X_cell,
                                )
                                .fit(
                                    disp=False,
                                    cov_type=cov_type,
                                    maxiter=maxiter,
                                )
                            )

                        # Capture silently.
                        cell_warning_records = (
                            _record_warnings(
                                cell_warnings,
                                factor_warning_log,
                                material=material,
                                factor=factor_name,
                                defect=defect,
                                category=category,
                                model_type=(
                                    "category-vs-rest"
                                ),
                            )
                        )

                        # =====================================
                        # NUMERICAL STABILITY CHECK
                        # =====================================

                        problems = (
                            _fit_problems(
                                cell_result,
                                cell_warnings,
                                require_bse=True,
                                require_pvalues=True,
                            )
                        )

                        if problems:

                            flags = (
                                _warning_flags(
                                    cell_warnings
                                )
                            )

                            if flags["runtime"]:

                                status = (
                                    "runtime_warning"
                                )

                            elif flags["hessian"]:

                                status = (
                                    "hessian_warning"
                                )

                            elif flags["convergence"]:

                                status = (
                                    "convergence_warning"
                                )

                            else:

                                status = (
                                    "invalid_model"
                                )

                            cell_status_df.loc[
                                defect,
                                category,
                            ] = status

                            # No detailed warnings printed here.
                            print(
                                "Skipping cell | "
                                f"Material={material} | "
                                f"Factor={factor_name} | "
                                f"Defect={defect} | "
                                f"Category={category} | "
                                f"{'; '.join(problems)}"
                            )

                            continue

                        # =====================================
                        # EXTRACT EFFECT
                        # =====================================

                        beta = (
                            cell_result.params.get(
                                "is_category",
                                np.nan,
                            )
                        )

                        se = (
                            cell_result.bse.get(
                                "is_category",
                                np.nan,
                            )
                        )

                        p_value = (
                            cell_result.pvalues.get(
                                "is_category",
                                np.nan,
                            )
                        )

                        if not np.all(
                            np.isfinite(
                                [
                                    beta,
                                    se,
                                    p_value,
                                ]
                            )
                        ):

                            cell_status_df.loc[
                                defect,
                                category,
                            ] = (
                                "non_finite_estimate"
                            )

                            print(
                                "Skipping cell | "
                                f"Material={material} | "
                                f"Factor={factor_name} | "
                                f"Defect={defect} | "
                                f"Category={category} | "
                                "non-finite coefficient, "
                                "SE or p-value"
                            )

                            continue

                        # =====================================
                        # CONFIDENCE INTERVAL
                        # =====================================

                        try:

                            ci_table = (
                                cell_result.conf_int(
                                    alpha=alpha
                                )
                            )

                            if hasattr(
                                ci_table,
                                "loc",
                            ):

                                ci_beta_low = (
                                    ci_table.loc[
                                        "is_category"
                                    ].iloc[0]
                                )

                                ci_beta_high = (
                                    ci_table.loc[
                                        "is_category"
                                    ].iloc[1]
                                )

                            else:

                                param_names = list(
                                    cell_result
                                    .params
                                    .index
                                )

                                position = (
                                    param_names.index(
                                        "is_category"
                                    )
                                )

                                ci_beta_low = (
                                    ci_table[
                                        position,
                                        0,
                                    ]
                                )

                                ci_beta_high = (
                                    ci_table[
                                        position,
                                        1,
                                    ]
                                )

                        except Exception as error:

                            cell_status_df.loc[
                                defect,
                                category,
                            ] = (
                                "ci_failed"
                            )

                            print(
                                "Skipping cell | "
                                f"Material={material} | "
                                f"Factor={factor_name} | "
                                f"Defect={defect} | "
                                f"Category={category} | "
                                "confidence interval failed: "
                                f"{type(error).__name__}: "
                                f"{error}"
                            )

                            continue

                        if not np.all(
                            np.isfinite(
                                [
                                    ci_beta_low,
                                    ci_beta_high,
                                ]
                            )
                        ):

                            cell_status_df.loc[
                                defect,
                                category,
                            ] = (
                                "non_finite_ci"
                            )

                            print(
                                "Skipping cell | "
                                f"Material={material} | "
                                f"Factor={factor_name} | "
                                f"Defect={defect} | "
                                f"Category={category} | "
                                "non-finite confidence interval"
                            )

                            continue

                        # =====================================
                        # IRR
                        # =====================================

                        with np.errstate(
                            over="ignore",
                            divide="ignore",
                            invalid="ignore",
                        ):

                            irr = np.exp(
                                beta
                            )

                            ci_low = np.exp(
                                ci_beta_low
                            )

                            ci_high = np.exp(
                                ci_beta_high
                            )

                        if not np.all(
                            np.isfinite(
                                [
                                    irr,
                                    ci_low,
                                    ci_high,
                                ]
                            )
                        ):

                            cell_status_df.loc[
                                defect,
                                category,
                            ] = (
                                "non_finite_irr_or_ci"
                            )

                            print(
                                "Skipping cell | "
                                f"Material={material} | "
                                f"Factor={factor_name} | "
                                f"Defect={defect} | "
                                f"Category={category} | "
                                "non-finite IRR or "
                                "confidence interval"
                            )

                            continue

                        if (
                            irr <= 0
                            or ci_low <= 0
                            or ci_high <= 0
                        ):

                            cell_status_df.loc[
                                defect,
                                category,
                            ] = (
                                "non_positive_irr_or_ci"
                            )

                            print(
                                "Skipping cell | "
                                f"Material={material} | "
                                f"Factor={factor_name} | "
                                f"Defect={defect} | "
                                f"Category={category} | "
                                "non-positive IRR or "
                                "confidence limit"
                            )

                            continue

                        # =====================================
                        # CLR
                        # =====================================

                        with np.errstate(
                            over="ignore",
                            divide="ignore",
                            invalid="ignore",
                        ):

                            clr = (
                                ci_high
                                / ci_low
                            )

                        if not np.isfinite(
                            clr
                        ):

                            cell_status_df.loc[
                                defect,
                                category,
                            ] = (
                                "non_finite_clr"
                            )

                            print(
                                "Skipping cell | "
                                f"Material={material} | "
                                f"Factor={factor_name} | "
                                f"Defect={defect} | "
                                f"Category={category} | "
                                "non-finite CLR"
                            )

                            continue

                        # =====================================
                        # MODEL ITSELF IS VALID
                        # =====================================

                        valid_cell_model_df.loc[
                            defect,
                            category,
                        ] = True

                        pval_df.loc[
                            defect,
                            category,
                        ] = p_value

                        valid_cell_models += 1

                        # Keep CLR for diagnostic purposes even
                        # if the estimate is subsequently rejected.
                        clr_df.loc[
                            defect,
                            category,
                        ] = clr

                        # =====================================
                        # PRECISION FILTER
                        # =====================================

                        if (
                            max_clr is not None
                            and clr > max_clr
                        ):

                            cell_status_df.loc[
                                defect,
                                category,
                            ] = (
                                "unstable_clr"
                            )

                            print(
                                "Skipping unstable IRR | "
                                f"Material={material} | "
                                f"Factor={factor_name} | "
                                f"Defect={defect} | "
                                f"Category={category} | "
                                f"IRR={irr:.4g} | "
                                f"95% CI="
                                f"[{ci_low:.4g}, "
                                f"{ci_high:.4g}] | "
                                f"CLR={clr:.2f} > "
                                f"{max_clr}"
                            )

                            # Warnings from this model are NOT
                            # printed because the IRR was rejected.
                            continue

                        # =====================================
                        # STABLE IRR — RETAIN RESULT
                        # =====================================

                        irr_df.loc[
                            defect,
                            category,
                        ] = irr

                        log2_irr_df.loc[
                            defect,
                            category,
                        ] = np.log2(
                            irr
                        )

                        ci_low_df.loc[
                            defect,
                            category,
                        ] = ci_low

                        ci_high_df.loc[
                            defect,
                            category,
                        ] = ci_high

                        stable_irr_df.loc[
                            defect,
                            category,
                        ] = True

                        cell_status_df.loc[
                            defect,
                            category,
                        ] = "stable"

                        stable_cell_models += 1

                        # =====================================
                        # ONLY NOW PRINT WARNINGS
                        # =====================================

                        _mark_warnings_retained(
                            cell_warning_records
                        )

                        _print_retained_warnings(
                            cell_warning_records
                        )

                    except Exception as error:

                        cell_status_df.loc[
                            defect,
                            category,
                        ] = (
                            "fit_failed"
                        )

                        print(
                            "Cell model failed | "
                            f"Material={material} | "
                            f"Factor={factor_name} | "
                            f"Defect={defect} | "
                            f"Category={category} | "
                            f"{type(error).__name__}: "
                            f"{error}"
                        )

                # =============================================
                # DEFECT-LEVEL DIAGNOSTICS
                # =============================================

                diagnostics.loc[
                    defect,
                    "valid_cell_models",
                ] = (
                    valid_cell_models
                )

                diagnostics.loc[
                    defect,
                    "stable_cell_models",
                ] = (
                    stable_cell_models
                )

                diagnostics.loc[
                    defect,
                    "status",
                ] = (
                    f"ok "
                    f"({valid_cell_models}/"
                    f"{len(valid_cats)} "
                    f"valid cells; "
                    f"{stable_cell_models} "
                    "stable IRRs)"
                )

            # =================================================
            # FDR — OMNIBUS
            # =================================================

            q_omnibus = pd.Series(
                np.nan,
                index=defect_order,
                dtype=float,
            )

            sig_omnibus = pd.Series(
                False,
                index=defect_order,
                dtype=bool,
            )

            valid_omnibus = (
                omnibus_p.notna()
            )

            if valid_omnibus.any():

                (
                    rejected,
                    q_values,
                    _,
                    _,
                ) = multipletests(
                    omnibus_p.loc[
                        valid_omnibus
                    ],
                    alpha=alpha,
                    method="fdr_bh",
                )

                q_omnibus.loc[
                    valid_omnibus
                ] = q_values

                sig_omnibus.loc[
                    valid_omnibus
                ] = rejected

            # =================================================
            # FDR — CELL TESTS
            # =================================================

            raw_cell_p = (
                pval_df.to_numpy(
                    dtype=float
                )
            )

            flat_cell_p = (
                raw_cell_p.ravel()
            )

            valid_cells = (
                np.isfinite(
                    flat_cell_p
                )
            )

            flat_cell_q = np.full(
                flat_cell_p.shape,
                np.nan,
                dtype=float,
            )

            flat_cell_significant = (
                np.zeros(
                    flat_cell_p.shape,
                    dtype=bool,
                )
            )

            if valid_cells.any():

                (
                    rejected,
                    q_values,
                    _,
                    _,
                ) = multipletests(
                    flat_cell_p[
                        valid_cells
                    ],
                    alpha=alpha,
                    method="fdr_bh",
                )

                flat_cell_q[
                    valid_cells
                ] = q_values

                flat_cell_significant[
                    valid_cells
                ] = rejected

            pval_fdr_df = pd.DataFrame(
                flat_cell_q.reshape(
                    pval_df.shape
                ),
                index=defect_order,
                columns=valid_cats,
            )

            sig_cell_df = pd.DataFrame(
                flat_cell_significant.reshape(
                    pval_df.shape
                ),
                index=defect_order,
                columns=valid_cats,
            )

            # =================================================
            # FINAL SIGNIFICANCE
            # =================================================

            omnibus_mask = pd.DataFrame(
                np.repeat(
                    sig_omnibus
                    .to_numpy()[:, None],
                    len(valid_cats),
                    axis=1,
                ),
                index=defect_order,
                columns=valid_cats,
            )

            significant_final = (
                sig_cell_df
                & omnibus_mask
                & stable_irr_df
            )

            # =================================================
            # DIAGNOSTICS
            # =================================================

            diagnostics[
                "p_omnibus"
            ] = omnibus_p

            diagnostics[
                "q_omnibus"
            ] = q_omnibus

            diagnostics[
                "significant_omnibus"
            ] = sig_omnibus

            # =================================================
            # WARNING LOG
            # =================================================

            warning_log_df = (
                pd.DataFrame(
                    factor_warning_log
                )
            )

            # =================================================
            # STORE RESULTS
            # =================================================

            results[
                material
            ][factor_name] = {

                # ONLY stable estimates
                "irr": irr_df,
                "log2_irr": log2_irr_df,

                "ci_low": ci_low_df,
                "ci_high": ci_high_df,

                # CLR can also contain values for models
                # excluded only because of poor precision.
                "clr": clr_df,

                "stable_irr": (
                    stable_irr_df
                ),

                "valid_cell_model": (
                    valid_cell_model_df
                ),

                "cell_status": (
                    cell_status_df
                ),

                "pval_raw": pval_df,
                "pval_fdr": pval_fdr_df,

                "significant_cell": (
                    sig_cell_df
                ),

                "positive_pipes_category": (
                    positive_category_df
                ),

                "positive_pipes_rest": (
                    positive_rest_df
                ),

                "pval_omnibus": (
                    omnibus_p
                ),

                "qval_omnibus": (
                    q_omnibus
                ),

                "significant_omnibus": (
                    sig_omnibus
                ),

                "significant_final": (
                    significant_final
                ),

                "diagnostics": (
                    diagnostics
                ),

                "warning_log": (
                    warning_log_df
                ),

                "valid_categories": (
                    valid_cats
                ),

                "all_categories": (
                    all_cats
                ),

                "max_clr": max_clr,

                "excluded": False,
            }

    # =========================================================
    # RELEVANT DEFECTS
    # =========================================================

    relevant_defects = {}

    for factor_name in factors_cat:

        relevant = []

        for defect in defect_order:

            for material in selected_materials:

                material_result = (
                    results
                    .get(
                        material,
                        {}
                    )
                    .get(
                        factor_name
                    )
                )

                if (
                    material_result
                    is not None
                    and
                    material_result.get(
                        "significant_final"
                    )
                    is not None
                    and
                    defect
                    in material_result[
                        "significant_final"
                    ].index
                    and
                    material_result[
                        "significant_final"
                    ]
                    .loc[
                        defect
                    ]
                    .any()
                ):

                    relevant.append(
                        defect
                    )

                    break

        relevant_defects[
            factor_name
        ] = relevant

    return (
        results,
        relevant_defects,
        defect_order,
    )

def plot_nb_matrix_of_matrices(
    results,
    factors_cat,
    selected_materials,
    get_categories_order,
    display_names,
    relevant_defects=None,
    cmap_name="BrBG",
    max_abs_log2=3.0,
    annotation_decimals=2,
    cell_width=0.65,
    cell_height=0.42,
    min_subplot_width=3.0,
    y_tick_length=3.5,
    colorbar_orientation="vertical",
    colorbar_fraction=0.018,
    colorbar_aspect=80,
):
    """
    Plot Negative Binomial results as a matrix of heatmaps.

    Outer matrix:
        rows = categorical factors
        columns = materials

    Inner heatmaps:
        rows = defect types from Defect_code_full
        columns = factor categories

    Only cells marked as significant_final are displayed. All other cells,
    including missing, excluded, non-converged, and non-significant results,
    are shown in grey without an annotation.

    Materials without any significant finite IRR across all selected factors
    are removed completely from the figure.

    The cell colour uses log2(IRR), centred at IRR = 1. The annotation shows
    the original IRR. Values outside +/- max_abs_log2 are clipped only for
    colour mapping; their displayed IRR is not changed.

    The model results must use Defect_code_full as their row index.
    """

    category_order = get_categories_order()

    if colorbar_orientation not in {"horizontal", "vertical"}:
        raise ValueError(
            "colorbar_orientation must be 'horizontal' or 'vertical'."
        )

    # Keep only materials with at least one significant, finite, positive IRR.
    plotted_materials = []

    for material in selected_materials:
        has_visible_result = False

        for factor_name in factors_cat:
            factor_result = (
                results
                .get(material, {})
                .get(factor_name)
            )

            if (
                factor_result is None
                or factor_result.get("irr") is None
                or factor_result.get("significant_final") is None
            ):
                continue

            irr = factor_result["irr"]
            significant = (
                factor_result["significant_final"]
                .reindex(index=irr.index, columns=irr.columns)
                .fillna(False)
                .astype(bool)
            )
            visible_values = irr.where(significant).to_numpy(dtype=float)

            if (
                np.isfinite(visible_values)
                & (visible_values > 0)
            ).any():
                has_visible_result = True
                break

        if has_visible_result:
            plotted_materials.append(material)

    if not plotted_materials:
        raise ValueError(
            "None of the selected materials has a significant finite IRR "
            "to plot."
        )

    # ------------------------------------------------------------
    # Determine which defects must be shown for each factor
    # ------------------------------------------------------------
    defects_by_factor = {}

    for factor_name in factors_cat:
        if relevant_defects is not None:
            candidate_defects = list(
                relevant_defects.get(factor_name, [])
            )
        else:
            candidate_defects = []

            for material in plotted_materials:
                factor_result = (
                    results
                    .get(material, {})
                    .get(factor_name)
                )

                if (
                    factor_result is None
                    or factor_result.get("significant_final") is None
                ):
                    continue

                for defect in factor_result["significant_final"].index:
                    if defect not in candidate_defects:
                        candidate_defects.append(defect)

        visible_defects = []

        for defect in candidate_defects:
            significant_somewhere = False

            for material in plotted_materials:
                factor_result = (
                    results
                    .get(material, {})
                    .get(factor_name)
                )

                if (
                    factor_result is None
                    or factor_result.get("significant_final") is None
                ):
                    continue

                significant = factor_result["significant_final"]

                if (
                    defect in significant.index
                    and significant.loc[defect].fillna(False).any()
                ):
                    significant_somewhere = True
                    break

            if significant_somewhere:
                visible_defects.append(defect)

        defects_by_factor[factor_name] = visible_defects

    # Factors with no significant defect would produce an empty row.
    plotted_factors = [
        factor_name
        for factor_name in factors_cat
        if len(defects_by_factor[factor_name]) > 0
    ]

    if not plotted_factors:
        raise ValueError(
            "There are no significant cells to plot after applying "
            "significant_final."
        )

    # ------------------------------------------------------------
    # Collect all visible IRRs to validate the colour range
    # ------------------------------------------------------------
    visible_log2_values = []

    for factor_name in plotted_factors:
        defects = defects_by_factor[factor_name]
        categories = list(category_order[factor_name])

        for material in plotted_materials:
            factor_result = (
                results
                .get(material, {})
                .get(factor_name)
            )

            if (
                factor_result is None
                or factor_result.get("irr") is None
                or factor_result.get("significant_final") is None
            ):
                continue

            irr = factor_result["irr"].reindex(
                index=defects,
                columns=categories,
            )
            significant = (
                factor_result["significant_final"]
                .reindex(index=defects, columns=categories)
                .fillna(False)
                .astype(bool)
            )

            values = irr.where(significant).to_numpy(dtype=float)
            valid = np.isfinite(values) & (values > 0)

            if valid.any():
                visible_log2_values.extend(
                    np.log2(values[valid]).tolist()
                )

    if not visible_log2_values:
        raise ValueError(
            "No finite positive IRR values remain after significance filtering."
        )

    if max_abs_log2 is None:
        max_abs_log2 = max(
            np.max(np.abs(visible_log2_values)),
            0.5,
        )

    if max_abs_log2 <= 0:
        raise ValueError("max_abs_log2 must be greater than zero.")

    # ------------------------------------------------------------
    # Create the outer matrix
    # ------------------------------------------------------------
    n_rows = len(plotted_factors)
    n_cols = len(plotted_materials)

    max_categories = max(
        len(category_order[factor_name])
        for factor_name in plotted_factors
    )
    height_ratios = [
        len(defects_by_factor[factor_name])
        for factor_name in plotted_factors
    ]

    subplot_width = max(
        min_subplot_width,
        max_categories * cell_width,
    )
    figure_width = max(6.0, n_cols * subplot_width)
    figure_height = max(
        3.0,
        sum(height_ratios) * cell_height + 1.4,
    )

    fig = plt.figure(
        figsize=(figure_width, figure_height),
        layout="constrained",
    )
    grid = fig.add_gridspec(
        nrows=n_rows,
        ncols=n_cols,
        height_ratios=height_ratios,
    )

    cmap = plt.get_cmap(cmap_name).copy()
    cmap.set_bad("#D9D9D9")

    norm = TwoSlopeNorm(
        vmin=-max_abs_log2,
        vcenter=0,
        vmax=max_abs_log2,
    )

    axes = np.empty((n_rows, n_cols), dtype=object)
    all_axes = []
    image = None

    for row_index, factor_name in enumerate(plotted_factors):
        defects = defects_by_factor[factor_name]
        categories = list(category_order[factor_name])
        shared_y_axis = None

        for column_index, material in enumerate(plotted_materials):
            ax = fig.add_subplot(
                grid[row_index, column_index],
                sharey=shared_y_axis,
            )

            if shared_y_axis is None:
                shared_y_axis = ax

            axes[row_index, column_index] = ax
            all_axes.append(ax)

            raw_irr = pd.DataFrame(
                np.nan,
                index=defects,
                columns=categories,
            )

            # Cells that did not satisfy min_positive_pipes_per_group = 1
            insufficient_positive = pd.DataFrame(
                False,
                index=defects,
                columns=categories,
            )

            factor_result = (
                results
                .get(material, {})
                .get(factor_name)
            )

            if (
                factor_result is not None
                and factor_result.get("irr") is not None
                and factor_result.get("significant_final") is not None
            ):
                irr = factor_result["irr"].reindex(
                    index=defects,
                    columns=categories,
                )
                significant = (
                    factor_result["significant_final"]
                    .reindex(index=defects, columns=categories)
                    .fillna(False)
                    .astype(bool)
                )

                raw_irr = irr.where(significant)
                raw_irr = raw_irr.where(raw_irr > 0)

                positive_category = (
                    factor_result["positive_pipes_category"]
                    .reindex(index=defects, columns=categories)
                )

                positive_rest = (
                    factor_result["positive_pipes_rest"]
                    .reindex(index=defects, columns=categories)
                )

                # A cell is classified as "insufficient positive pipes"
                # only when the counts were actually calculated and at least
                # one of the two comparison groups has fewer than 1 positive pipe.
                counts_available = (
                    positive_category.notna()
                    & positive_rest.notna()
                )

                insufficient_positive = (
                    counts_available
                    & (
                        (positive_category < 1)
                        | (positive_rest < 1)
                    )
                )

                raw_irr = irr.where(significant)
                raw_irr = raw_irr.where(raw_irr > 0)

            raw_values = raw_irr.to_numpy(dtype=float)
            log2_values = np.full(raw_values.shape, np.nan)
            valid_values = np.isfinite(raw_values) & (raw_values > 0)
            log2_values[valid_values] = np.log2(raw_values[valid_values])

            image = ax.imshow(
                np.ma.masked_invalid(log2_values),
                cmap=cmap,
                norm=norm,
                aspect="auto",
                interpolation="none",
            )

            # ---------------------------------------------------------
            # White cells = insufficient positive pipes for comparison
            # ---------------------------------------------------------
            insufficient_array = insufficient_positive.to_numpy(dtype=bool)

            for defect_index in range(len(defects)):
                for category_index in range(len(categories)):

                    if insufficient_array[defect_index, category_index]:

                        rect = Rectangle(
                            (
                                category_index - 0.5,
                                defect_index - 0.5,
                            ),
                            1,
                            1,
                            facecolor="#7A7A7A",
                            edgecolor="white",
                            linewidth=1.0,
                            zorder=1,
                        )

                        ax.add_patch(rect)

            ax.set_xticks(np.arange(len(categories)))
            ax.set_xticklabels(
                [
                    display_names.get(category, str(category))
                    for category in categories
                ],
                rotation=45,
                ha="right",
                rotation_mode="anchor",
                fontsize=11,
            )

            ax.set_yticks(np.arange(len(defects)))

            if column_index == 0:
                # Result indices come directly from Defect_code_full.
                ax.set_yticklabels(defects, fontsize=11)
                ax.tick_params(
                    axis="y",
                    which="major",
                    left=True,
                    length=y_tick_length,
                    width=0.8,
                    direction="out",
                )
                ax.set_ylabel(
                    display_names.get(factor_name, factor_name),
                    fontsize=14,
                    fontweight="bold",
                    labelpad=12,
                )
            else:
                ax.tick_params(
                    axis="y",
                    which="major",
                    left=False,
                    labelleft=False,
                )

            if row_index == 0:
                ax.set_title(
                    display_names.get(material, material),
                    fontsize=14,
                    fontweight="bold",
                    pad=10,
                )

            ax.set_xticks(
                np.arange(-0.5, len(categories), 1),
                minor=True,
            )
            ax.set_yticks(
                np.arange(-0.5, len(defects), 1),
                minor=True,
            )
            ax.grid(
                which="minor",
                color="white",
                linewidth=1.0,
            )
            ax.tick_params(which="minor", bottom=False, left=False)

            for defect_index in range(len(defects)):
                for category_index in range(len(categories)):
                    value = raw_values[defect_index, category_index]

                    if not np.isfinite(value):
                        continue

                    if value >= 1000 or value < 0.01:
                        annotation = f"{value:.1e}"
                    else:
                        annotation = f"{value:.{annotation_decimals}f}"

                    colour_value = np.clip(
                        log2_values[defect_index, category_index],
                        -max_abs_log2,
                        max_abs_log2,
                    )
                    red, green, blue, _ = cmap(norm(colour_value))
                    luminance = (
                        0.2126 * red
                        + 0.7152 * green
                        + 0.0722 * blue
                    )
                    text_colour = "black" if luminance > 0.55 else "white"

                    ax.text(
                        category_index,
                        defect_index,
                        annotation,
                        ha="center",
                        va="center",
                        fontsize=10,
                        color=text_colour,
                    )

            ax.set_xlim(-0.5, len(categories) - 0.5)
            ax.set_ylim(len(defects) - 0.5, -0.5)

    colourbar = fig.colorbar(
        image,
        ax=all_axes,
        orientation=colorbar_orientation,
        fraction=colorbar_fraction,
        pad=0.03,
        aspect=colorbar_aspect,
    )

    colourbar_ticks = np.linspace(
        -max_abs_log2,
        max_abs_log2,
        7,
    )
    colourbar.set_ticks(colourbar_ticks)
    colourbar.set_ticklabels(
        [f"{2 ** value:.2g}" for value in colourbar_ticks]
    )
    colourbar.set_label(
        "IRR (colour displayed on a log2 scale)",
        fontsize=12,
    )
    # ------------------------------------------------------------
    # Legend for cells excluded due to insufficient defect cases
    # ------------------------------------------------------------
    grey_patch = Patch(
        facecolor="#7A7A7A",
        edgecolor="white",
        label="Not compared: no defect-positive pipes in category or rest"
    )

    fig.legend(
        handles=[grey_patch],
        loc="upper right",
        bbox_to_anchor=(0.95, 1.025),
        frameon=False,
        fontsize=14,
    )

    plt.show()
    return fig, axes